### ISSUE TITLE
Failed delivery to GCP

### ISSUE THREAD

**Issue by benhylau** [groundupworks/wings#13]
Notification suggests successful delivery to GCP endpoint, but the file is not actually uploaded.

This is the bug reported by Nathaniel and probably the same one experienced by Patience. This happens on multiple Android devices, with many printers, so the issue is more widespread than a particular phone/printer.

**Comment by benhylau** [comment]
+report by Farhan

**Comment by benhylau** [comment]
We are getting back data from our analytics. All failures are due to this error returned from GCP. Looks like GCP converts JPG images to PDF for certain printers, and Google is having trouble converting some of the JPG files we are sending. Looks like we have a path forward on this issue.

![screen shot 2015-02-27 at 8 20 51 pm](https://cloud.githubusercontent.com/assets/2261308/6424027/388ee63a-bebe-11e4-9a24-2540a842a236.png)

**Comment by desibelle** [comment]
Every single GCP failure over last week was due to this :cry:

**Comment by benhylau** [comment]
Fixed with https://github.com/groundupworks/wings/pull/25

**Comment by benhylau** [comment]
@desibelle Actually it was failing for some printers that don't support colour printing too. Google throws the same PDF error in that case. Pretty much PDF error is thrown for whatever failure.

Removing the hardcode to colour printing fixes it.
